
import java.awt.Color;

import java.awt.Graphics;
import java.awt.Point;
import java.util.ArrayList;

import javax.swing.JColorChooser;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ly Tan loi
 */
public class DrawWithMouse extends javax.swing.JFrame {

    Graphics g = null;
    Point p1 = null, p2 = null;
    Color color = Color.RED;

    public DrawWithMouse() {
        initComponents();
        g = this.pLines.getGraphics();
        this.rdFill.setEnabled(false);
    }

    ArrayList<Point> line = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnColor = new javax.swing.JButton();
        rdDraw = new javax.swing.JRadioButton();
        rdFill = new javax.swing.JRadioButton();
        JTabbedPanel = new javax.swing.JTabbedPane();
        pLines = new javax.swing.JPanel();
        pEllipses = new javax.swing.JPanel();
        pRectangle = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Draw with Mouse");

        btnColor.setText("Select Color");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdDraw);
        rdDraw.setSelected(true);
        rdDraw.setText("Draw only");

        buttonGroup1.add(rdFill);
        rdFill.setText("Draw and Fill");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnColor)
                .addGap(50, 50, 50)
                .addComponent(rdDraw)
                .addGap(29, 29, 29)
                .addComponent(rdFill)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColor)
                    .addComponent(rdDraw)
                    .addComponent(rdFill))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        JTabbedPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTabbedPanelMouseClicked(evt);
            }
        });

        pLines.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pLinesMouseDragged(evt);
            }
        });
        pLines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pLinesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pLinesMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pLinesLayout = new javax.swing.GroupLayout(pLines);
        pLines.setLayout(pLinesLayout);
        pLinesLayout.setHorizontalGroup(
            pLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        pLinesLayout.setVerticalGroup(
            pLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        JTabbedPanel.addTab("Lines", pLines);

        pEllipses.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pEllipsesMouseDragged(evt);
            }
        });
        pEllipses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pEllipsesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pEllipsesMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pEllipsesLayout = new javax.swing.GroupLayout(pEllipses);
        pEllipses.setLayout(pEllipsesLayout);
        pEllipsesLayout.setHorizontalGroup(
            pEllipsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        pEllipsesLayout.setVerticalGroup(
            pEllipsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        JTabbedPanel.addTab("Ellipses", pEllipses);

        pRectangle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pRectangleMouseDragged(evt);
            }
        });
        pRectangle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pRectangleMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pRectangleMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pRectangleMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pRectangleLayout = new javax.swing.GroupLayout(pRectangle);
        pRectangle.setLayout(pRectangleLayout);
        pRectangleLayout.setHorizontalGroup(
            pRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        pRectangleLayout.setVerticalGroup(
            pRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        JTabbedPanel.addTab("Rectangles", pRectangle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JTabbedPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTabbedPanel))
        );

        JTabbedPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        color = JColorChooser.showDialog(this, "Choose a color", Color.BLACK);
        g.setColor(color);
    }//GEN-LAST:event_btnColorActionPerformed

    private void pRectangleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pRectangleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pRectangleMouseClicked

    private void JTabbedPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTabbedPanelMouseClicked
        int index = this.JTabbedPanel.getSelectedIndex();
        switch (index) {
            case 0: {
                g = pLines.getGraphics();
                this.rdDraw.setSelected(true);
                this.rdFill.setEnabled(false);
                break;
            }
            case 1: {
                g = pEllipses.getGraphics();
                this.rdFill.setEnabled(true);
                break;
            }
            case 2: {
                g = pRectangle.getGraphics();
                this.rdFill.setEnabled(true);
                break;
            }
        }
        g.setColor(color);
    }//GEN-LAST:event_JTabbedPanelMouseClicked

//    public void drawAll(){
//        int index = this.JTabbedPanel.getSelectedIndex();
//        switch(index){
//            case 0:{
//                for(int i =0; i<line.size(); i++){
//                    g.setColor(color);
//                    g.drawLine(line.get(1).x, line.get(1).y, line.get(2).x, line.get(i).y);
//                    return;
//                }
//                break;
//            }
//            case 1:{
//                break;
//            }
//            case 2:{
//                break;
//            }
//        }
//    }
    private void pLinesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLinesMousePressed
        p1 = evt.getPoint();
        line.add(p1);
    }//GEN-LAST:event_pLinesMousePressed

    private void pLinesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLinesMouseReleased
        p2 = evt.getPoint();
        g.drawLine(p1.x, p1.y, p2.x, p2.y);
        line.add(p2);
        p1 = p2 = null;
    }//GEN-LAST:event_pLinesMouseReleased

    private void pEllipsesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEllipsesMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_pEllipsesMousePressed

    private void pEllipsesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEllipsesMouseReleased
        p2 = evt.getPoint();
        int left = p1.x < p2.x ? p1.x : p2.x;
        int top = p1.y < p2.y ? p1.y : p2.y;
        int width = p1.x - p2.x;
        if (width < 0) {
            width = -width;
        }
        int height = p1.y - p2.y;
        if (height < 0) {
            height = -height;
        }
        if (rdDraw.isSelected()) {
            g.drawOval(left, top, width, height);
        } else {
            g.fillOval(left, top, width, height);
        }
        p1 = p2 = null;
    }//GEN-LAST:event_pEllipsesMouseReleased

    private void pRectangleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pRectangleMousePressed
        p1 = evt.getPoint();

    }//GEN-LAST:event_pRectangleMousePressed

    private void pRectangleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pRectangleMouseReleased
        p2 = evt.getPoint();
        int left = p1.x < p2.x ? p1.x : p2.x;
        int top = p1.y < p2.y ? p1.y : p2.y;
        int width = p1.x - p2.x;
        if (width < 0) {
            width = -width;
        }
        int height = p1.y - p2.y;
        if (height < 0) {
            height = -height;
        }
        if (rdDraw.isSelected()) {

            g.drawRect(left, top, width, height);
        } else {
            g.fillRect(left, top, width, height);
        }
        p1 = p2 = null;
    }//GEN-LAST:event_pRectangleMouseReleased

    private void pLinesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLinesMouseDragged

        p2 = evt.getPoint();
        g.drawLine(p1.x, p1.y, p2.x, p2.y);
        pLines.updateUI();


    }//GEN-LAST:event_pLinesMouseDragged

    private void pEllipsesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEllipsesMouseDragged
        p2 = evt.getPoint();
        int left = p1.x < p2.x ? p1.x : p2.x;
        int top = p1.y < p2.y ? p1.y : p2.y;
        int width = p1.x - p2.x;
        if (width < 0) {
            width = -width;
        }
        int height = p1.y - p2.y;
        if (height < 0) {
            height = -height;
        }
        if (rdDraw.isSelected()) {

            g.drawOval(left, top, width, height);
        } else {

            g.fillOval(left, top, width, height);
        }
        pEllipses.updateUI();
    }//GEN-LAST:event_pEllipsesMouseDragged

    private void pRectangleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pRectangleMouseDragged
        p2 = evt.getPoint();
        int left = p1.x < p2.x ? p1.x : p2.x;
        int top = p1.y < p2.y ? p1.y : p2.y;
        int width = p1.x - p2.x;
        if (width < 0) {
            width = -width;
        }
        int height = p1.y - p2.y;
        if (height < 0) {
            height = -height;
        }
        if (rdDraw.isSelected()) {

            g.drawRect(left, top, width, height);
        } else {
            g.fillRect(left, top, width, height);
        }
        pRectangle.updateUI();
    }//GEN-LAST:event_pRectangleMouseDragged

    @Override
    public void paintComponents(Graphics g) {
        super.paintComponents(g);

        g.drawLine(line.get(0).x, line.get(0).y, line.get(1).x, line.get(1).y);
    }
    public void paint(Graphics g){
        super.paint(g);
        try {
            g.setColor(color);
            g.drawLine(line.get(0).x, line.get(0).y, line.get(1).x, line.get(1).y);
        } catch (Exception e) {
        }
        
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawWithMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawWithMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawWithMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawWithMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DrawWithMouse r = new DrawWithMouse();
                r.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabbedPanel;
    private javax.swing.JButton btnColor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pEllipses;
    private javax.swing.JPanel pLines;
    private javax.swing.JPanel pRectangle;
    private javax.swing.JRadioButton rdDraw;
    private javax.swing.JRadioButton rdFill;
    // End of variables declaration//GEN-END:variables

}
