
import java.text.DateFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ly Tan loi
 */
public class ManagerProgram extends javax.swing.JFrame {

    ItemDBAccess dbAccess = null;
    Suppliers suppliers;
    Items items;
    ItemFullModel itemModel;
    SupplierFullModel supplierFullModel;
    boolean addNew = false;
    String country;
    String language;
    ResourceBundle resource;
    Date today;
    SimpleDateFormat formatter;
    DateFormatSymbols pattern;
    String[] session = {"Buổi Sáng", "Buổi Chiều"};

    /**
     * Creates new form ManagerProgram
     */
    public ManagerProgram() {
        initComponents();
        jTabbedPane1.setSize(this.getSize().width - 10, this.getSize().height - 30);
        dbAccess = new ItemDBAccess();
        suppliers = new Suppliers();
        suppliers.loadFromDB(dbAccess);
        items = new Items();
        int getAll = 3;
        items.loadFromDB(dbAccess, suppliers, getAll);
        itemModel = new ItemFullModel(items);
        supplierFullModel = new SupplierFullModel(suppliers);
        setupModel();
        this.country = new String("US");
        this.language = new String("en");
        pattern = new DateFormatSymbols(new Locale(language, country));
        setUpGUI();
    }

    public void setUpGUI() {
        Locale curLocale = new Locale(language, country);
        String base = "resource/data";
        resource = ResourceBundle.getBundle(base, curLocale);
        this.setTitle(resource.getString("prgTitle"));
        lbSupCode.setText(resource.getString("lbSupCode"));
        lbSupName.setText(resource.getString("lbSupName"));
        lbAddress.setText(resource.getString("lbAddress"));
        lbColloborating.setText(resource.getString("lbColloborating"));
        btnSupNew.setText(resource.getString("btnSupNew"));
        btnSave.setText(resource.getString("btnSupSave"));
        btnSupRemove.setText(resource.getString("btnSupDelete"));
        //Item
        lbItemCode.setText(resource.getString("lbItemCode"));
        lbItemName.setText(resource.getString("lbItemName"));
        lbSupplier.setText(resource.getString("lbSupplier"));
        lbSupplying.setText(resource.getString("lbSupplying"));
        btnAddNew.setText(resource.getString("btnNew"));
        btnDelete.setText(resource.getString("btnDelete"));
        formatter = new SimpleDateFormat("EEEE dd MMMM yyyy hh:mm aaa", pattern);
        today = new Date();
        lbDateTime.setText(formatter.format(today));

    }

    private void setupModel() {
        tblItems.setModel(itemModel);
        tblSuppliers.setModel(supplierFullModel);
        this.cbSupplier.setModel(new DefaultComboBoxModel(suppliers));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSuppliers = new javax.swing.JTable();
        lbSupCode = new javax.swing.JLabel();
        lbSupName = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        lbColloborating = new javax.swing.JLabel();
        txtSupCode = new javax.swing.JTextField();
        txtSupName = new javax.swing.JTextField();
        txtSupAddress = new javax.swing.JTextField();
        chbColoborating = new javax.swing.JCheckBox();
        btnSupNew = new javax.swing.JButton();
        btnSupSave = new javax.swing.JButton();
        btnSupRemove = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        lbItemCode = new javax.swing.JLabel();
        lbItemName = new javax.swing.JLabel();
        lbSupplier = new javax.swing.JLabel();
        lbUnit = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbSupplying = new javax.swing.JLabel();
        btnAddNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        cbSupplier = new javax.swing.JComboBox();
        txtUnit = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        chbSupplying = new javax.swing.JCheckBox();
        cbLanguage = new javax.swing.JComboBox();
        lbDateTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuppliersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSuppliers);

        lbSupCode.setText("SupCode:");

        lbSupName.setText("SupName:");

        lbAddress.setText("Address:");

        lbColloborating.setText("Colloborating:");

        btnSupNew.setText("New");
        btnSupNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupNewActionPerformed(evt);
            }
        });

        btnSupSave.setText("Save");
        btnSupSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupSaveActionPerformed(evt);
            }
        });

        btnSupRemove.setText("Remove");
        btnSupRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbSupCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSupCode, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbSupName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSupName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbAddress)
                        .addGap(18, 18, 18)
                        .addComponent(txtSupAddress))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbColloborating)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbColoborating)))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(btnSupNew, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSupSave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btnSupRemove)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSupCode)
                            .addComponent(txtSupCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSupName)
                            .addComponent(txtSupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAddress)
                            .addComponent(txtSupAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbColloborating)
                            .addComponent(chbColoborating)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupNew)
                    .addComponent(btnSupSave)
                    .addComponent(btnSupRemove))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manage Suppliers", jPanel1);

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblItemsMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblItems);

        lbItemCode.setText("Item code:");

        lbItemName.setText("Item name:");

        lbSupplier.setText("Supplier:");

        lbUnit.setText("Unit:");

        lbPrice.setText("Price:");

        lbSupplying.setText("Supplying:");

        btnAddNew.setText("Add New");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cbSupplier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SS", "AP", "NA", "CA", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbSupplying)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbSupplying))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbItemCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbItemName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbUnit)
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddNew)
                .addGap(37, 37, 37)
                .addComponent(btnSave)
                .addGap(39, 39, 39)
                .addComponent(btnDelete)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbItemCode)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbItemName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSupplier)
                            .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUnit)
                            .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrice)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSupplying)
                    .addComponent(chbSupplying))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNew)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Item", jPanel2);

        cbLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Tiếng Việt" }));
        cbLanguage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLanguageItemStateChanged(evt);
            }
        });

        lbDateTime.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbDateTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lbDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        addNew = true;
        txtCode.setText("");
        txtName.setText("");
        txtCode.setEditable(true);
        txtCode.requestFocus();
        cbSupplier.setSelectedIndex(0);
        txtUnit.setText("");
        txtPrice.setText("");
        chbSupplying.setSelected(true);
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String itemCode = txtCode.getText();

        String itemName = txtName.getText();
        Supplier supplier = (Supplier) cbSupplier.getSelectedItem();
        String supCode = supplier.getSupCode();
        String unit = txtUnit.getText();
        int price = Integer.parseInt(txtPrice.getText());
        boolean supplying = chbSupplying.isSelected();
        Item item = new Item(itemCode, itemName, supplier, unit, price, supplying);
        String sql = "";
        if (addNew == true) {
            if (!se1069.BasicValidator.validateCode(itemCode, "L[0-9]{3}")) {
                JOptionPane.showMessageDialog(this, "Invalid Code");
                return;
            }
            for (int i = 0; i < items.size(); i++) {
                if (items.get(i).getItemCode().equalsIgnoreCase(txtCode.getText())) {
                    JOptionPane.showMessageDialog(this, "Invalid Code");
                    return;
                }
            }
            sql = "insert into Items values('" + itemCode + "','" + itemName + "','" + supCode + "','" + unit + "'," + price + "," + (supplying ? 1 : 0) + ")";
        } else {
            sql = "update Items set " + "itemName='" + itemName + "'," + "supCode='" + supCode + "',unit='" + unit + "',price=" + price + ",supplying=" + (supplying ? 1 : 0) + "where itemcode='" + itemCode + "'";
        }
        JOptionPane.showMessageDialog(this, sql);
        String msg = " An item has been added/updated.";
        try {
            int n = dbAccess.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showMessageDialog(this, msg);
                if (addNew == false) {
                    int pos = tblItems.getSelectedRow();
                    itemModel.getItems().set(pos, item);
                } else {
                    itemModel.getItems().add(item);
                }
                tblItems.updateUI();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        addNew = false;
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int pos = tblItems.getSelectedRow();
        String itemCode = txtCode.getText();
        String sql = "Delete from Items where itemCode='" + itemCode + "'";
        JOptionPane.showConfirmDialog(this, sql);
        String msg = "The item " + itemCode + " has been deleted from DB!";
        try {
            int n = dbAccess.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showConfirmDialog(this, msg);
                itemModel.getItems().removeElementAt(pos);
                tblItems.updateUI();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblItemsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseReleased
        int row = tblItems.getSelectedRow();
        int col = tblItems.getSelectedColumn();
        tblItems.getCellEditor(row, col).cancelCellEditing();
    }//GEN-LAST:event_tblItemsMouseReleased

    private void tblItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseClicked
        addNew = false;
        int pos = tblItems.getSelectedRow();
        Item item = itemModel.getItems().get(pos);
        txtCode.setText(item.getItemCode());
        txtCode.setEditable(false);
        txtName.setText(item.getItemName());
        int index = suppliers.find(item.getSupplier().getSupCode());
        cbSupplier.setSelectedIndex(index);
        txtUnit.setText("" + item.getUnit());
        txtPrice.setText("" + item.getPrice());
        chbSupplying.setSelected(item.isSupplying());
    }//GEN-LAST:event_tblItemsMouseClicked

    private void btnSupNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupNewActionPerformed
        addNew = true;
        txtSupCode.setText("");
        txtSupName.setText("");
        txtSupCode.setEditable(true);
        txtSupCode.requestFocus();
        txtSupAddress.setText("");
        chbSupplying.setSelected(true);
    }//GEN-LAST:event_btnSupNewActionPerformed

    private void btnSupSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupSaveActionPerformed
        String supCode = txtSupCode.getText();
        String supName = txtSupName.getText();
        String address = txtSupAddress.getText();
        boolean colloborating = chbColoborating.isSelected();
        Supplier supplier = new Supplier(supCode, supName, address, colloborating);
        String sql = "";
        if (addNew == true) {
            if (!se1069.BasicValidator.validateCode(supCode, "[a-zA-Z]{2}")) {
                JOptionPane.showMessageDialog(this, "Invalid Code");
                return;
            }
            for (int i = 0; i < suppliers.size(); i++) {
                if (suppliers.get(i).getSupCode().equalsIgnoreCase(txtSupCode.getText())) {
                    JOptionPane.showMessageDialog(this, "Invalid Code");
                    return;
                }
            }

            sql = "insert into Suppliers values('" + supCode + "','" + supName + "','" + address + "'," + (colloborating ? 1 : 0) + ")";
        } else {
            sql = "update Suppliers set " + "SupName='" + supName + "'," + "Address='" + address + "',colloborating=" + (colloborating ? 1 : 0) + "where SupCode='" + supCode + "'";
        }
        JOptionPane.showMessageDialog(this, sql);
        String msg = " An item has been added/updated.";
        try {
            int n = dbAccess.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showMessageDialog(this, msg);
                if (addNew == false) {
                    int pos = tblItems.getSelectedRow();
                    supplierFullModel.getSuppliers().set(pos, supplier);
                } else {
                    supplierFullModel.getSuppliers().add(supplier);
                }
                tblSuppliers.updateUI();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        addNew = false;
    }//GEN-LAST:event_btnSupSaveActionPerformed

    private void btnSupRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupRemoveActionPerformed
        int pos = tblSuppliers.getSelectedRow();
        String supCode = txtSupCode.getText();
        String sql = "Delete from Suppliers where SupCode='" + supCode + "'";
        String sql2 = "Delete from Items where SupCode = '" + supCode + "'";
        JOptionPane.showConfirmDialog(this, sql);
        String msg = "The supplier " + supCode + " and all items have been deleted from DB!";
        try {
            int r = JOptionPane.showConfirmDialog(this, "Delete the supplier and its all items?");
            if (r == JOptionPane.YES_OPTION) {
                int n = dbAccess.executeUpdate(sql);
                int n2 = dbAccess.executeUpdate(sql2);
                if (n > 0) {
                    JOptionPane.showConfirmDialog(this, msg);
                    supplierFullModel.getSuppliers().removeElementAt(pos);
                    tblSuppliers.updateUI();
                    tblItems.updateUI();
                }
            }
            else if(r == JOptionPane.NO_OPTION){
                return;
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e);
        }
        dbAccess = new ItemDBAccess();
        suppliers = new Suppliers();
        suppliers.loadFromDB(dbAccess);
        items = new Items();
        int getAll = 3;
        items.loadFromDB(dbAccess, suppliers, getAll);
        itemModel = new ItemFullModel(items);
        supplierFullModel = new SupplierFullModel(suppliers);
        setupModel();
    }//GEN-LAST:event_btnSupRemoveActionPerformed

    private void tblSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuppliersMouseClicked
        addNew = false;
        int pos = tblSuppliers.getSelectedRow();
        Supplier supplier = supplierFullModel.getSuppliers().get(pos);
        txtSupCode.setText(supplier.getSupCode());
        txtSupCode.setEditable(false);
        txtSupName.setText(supplier.getSupName());
        txtSupAddress.setText(supplier.getAddress());
        chbColoborating.setSelected(supplier.isColloborating());
    }//GEN-LAST:event_tblSuppliersMouseClicked

    private void cbLanguageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLanguageItemStateChanged
        if (((String) cbLanguage.getSelectedItem()).equals("English")) {
            this.language = new String("en");
            this.country = new String("US");
            pattern = new DateFormatSymbols(new Locale(language, country));
            jTabbedPane1.setTitleAt(0, "Manage Suppliers");
            jTabbedPane1.setTitleAt(1, "Manage Items");
        } else {
            this.language = new String("vi");
            this.country = new String("VN");
            pattern = new DateFormatSymbols(new Locale(language, country));
            pattern.setAmPmStrings(session);
            jTabbedPane1.setTitleAt(0, "Nhà cung cấp");
            jTabbedPane1.setTitleAt(1, "Sản phẩm");
            tblSuppliers.getModel().setValueAt((String)"Ma", 0, 0);
        }
        setUpGUI();
    }//GEN-LAST:event_cbLanguageItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSupNew;
    private javax.swing.JButton btnSupRemove;
    private javax.swing.JButton btnSupSave;
    private javax.swing.JComboBox cbLanguage;
    private javax.swing.JComboBox cbSupplier;
    private javax.swing.JCheckBox chbColoborating;
    private javax.swing.JCheckBox chbSupplying;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbColloborating;
    private javax.swing.JLabel lbDateTime;
    private javax.swing.JLabel lbItemCode;
    private javax.swing.JLabel lbItemName;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbSupCode;
    private javax.swing.JLabel lbSupName;
    private javax.swing.JLabel lbSupplier;
    private javax.swing.JLabel lbSupplying;
    private javax.swing.JLabel lbUnit;
    private javax.swing.JTable tblItems;
    private javax.swing.JTable tblSuppliers;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSupAddress;
    private javax.swing.JTextField txtSupCode;
    private javax.swing.JTextField txtSupName;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
